package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.AbstractC5109i;
import com.google.android.gms.common.api.AbstractC5207q;
import com.google.android.gms.common.api.AbstractC5208r;
import com.google.android.gms.common.api.InterfaceC5204n;
import com.google.android.gms.common.api.InterfaceC5205o;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

/* renamed from: com.google.android.gms.common.api.internal.i1 */
/* loaded from: classes.dex */
public final class C5145i1<R extends InterfaceC5204n> extends AbstractC5109i<R> {

    /* renamed from: a */
    private final Status f10492a;

    /* JADX INFO: Access modifiers changed from: package-private */
    /* renamed from: a */
    public final Status m13074a() {
        return this.f10492a;
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final void addStatusListener(AbstractC5109i.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final R await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final R await(long j10, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final void setResultCallback(InterfaceC5205o<? super R> interfaceC5205o) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final void setResultCallback(InterfaceC5205o<? super R> interfaceC5205o, long j10, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC5109i
    public final <S extends InterfaceC5204n> AbstractC5208r<S> then(AbstractC5207q<? super R, ? extends S> abstractC5207q) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
