package com.google.android.gms.internal.mlkit_common;

import io.flutter.plugins.firebase.analytics.Constants;
import jd.c;
import jd.d;
import jd.e;

/* loaded from: classes2.dex */
final class zzgl implements d {
    private static final c zzA;
    private static final c zzB;
    private static final c zzC;
    private static final c zzD;
    private static final c zzE;
    private static final c zzF;
    private static final c zzG;
    private static final c zzH;
    private static final c zzI;
    private static final c zzJ;
    private static final c zzK;
    private static final c zzL;
    private static final c zzM;
    private static final c zzN;
    private static final c zzO;
    private static final c zzP;
    private static final c zzQ;
    private static final c zzR;
    private static final c zzS;
    private static final c zzT;
    private static final c zzU;
    private static final c zzV;
    private static final c zzW;
    private static final c zzX;
    private static final c zzY;
    private static final c zzZ;
    static final zzgl zza = new zzgl();
    private static final c zzaA;
    private static final c zzaB;
    private static final c zzaC;
    private static final c zzaD;
    private static final c zzaE;
    private static final c zzaF;
    private static final c zzaG;
    private static final c zzaH;
    private static final c zzaI;
    private static final c zzaJ;
    private static final c zzaK;
    private static final c zzaL;
    private static final c zzaM;
    private static final c zzaN;
    private static final c zzaO;
    private static final c zzaP;
    private static final c zzaQ;
    private static final c zzaR;
    private static final c zzaS;
    private static final c zzaT;
    private static final c zzaU;
    private static final c zzaV;
    private static final c zzaW;
    private static final c zzaX;
    private static final c zzaY;
    private static final c zzaZ;
    private static final c zzaa;
    private static final c zzab;
    private static final c zzac;
    private static final c zzad;
    private static final c zzae;
    private static final c zzaf;
    private static final c zzag;
    private static final c zzah;
    private static final c zzai;
    private static final c zzaj;
    private static final c zzak;
    private static final c zzal;
    private static final c zzam;
    private static final c zzan;
    private static final c zzao;
    private static final c zzap;
    private static final c zzaq;
    private static final c zzar;
    private static final c zzas;
    private static final c zzat;
    private static final c zzau;
    private static final c zzav;
    private static final c zzaw;
    private static final c zzax;
    private static final c zzay;
    private static final c zzaz;
    private static final c zzb;
    private static final c zzba;
    private static final c zzbb;
    private static final c zzbc;
    private static final c zzc;
    private static final c zzd;
    private static final c zze;
    private static final c zzf;
    private static final c zzg;
    private static final c zzh;
    private static final c zzi;
    private static final c zzj;
    private static final c zzk;
    private static final c zzl;
    private static final c zzm;
    private static final c zzn;
    private static final c zzo;
    private static final c zzp;
    private static final c zzq;
    private static final c zzr;
    private static final c zzs;
    private static final c zzt;
    private static final c zzu;
    private static final c zzv;
    private static final c zzw;
    private static final c zzx;
    private static final c zzy;
    private static final c zzz;

    static {
        c.b a10 = c.a("systemInfo");
        zzbk zzbkVar = new zzbk();
        zzbkVar.zza(1);
        zzb = a10.b(zzbkVar.zzb()).a();
        c.b a11 = c.a(Constants.EVENT_NAME);
        zzbk zzbkVar2 = new zzbk();
        zzbkVar2.zza(2);
        zzc = a11.b(zzbkVar2.zzb()).a();
        c.b a12 = c.a("isThickClient");
        zzbk zzbkVar3 = new zzbk();
        zzbkVar3.zza(37);
        zzd = a12.b(zzbkVar3.zzb()).a();
        c.b a13 = c.a("clientType");
        zzbk zzbkVar4 = new zzbk();
        zzbkVar4.zza(61);
        zze = a13.b(zzbkVar4.zzb()).a();
        c.b a14 = c.a("modelDownloadLogEvent");
        zzbk zzbkVar5 = new zzbk();
        zzbkVar5.zza(3);
        zzf = a14.b(zzbkVar5.zzb()).a();
        c.b a15 = c.a("customModelLoadLogEvent");
        zzbk zzbkVar6 = new zzbk();
        zzbkVar6.zza(20);
        zzg = a15.b(zzbkVar6.zzb()).a();
        c.b a16 = c.a("customModelInferenceLogEvent");
        zzbk zzbkVar7 = new zzbk();
        zzbkVar7.zza(4);
        zzh = a16.b(zzbkVar7.zzb()).a();
        c.b a17 = c.a("customModelCreateLogEvent");
        zzbk zzbkVar8 = new zzbk();
        zzbkVar8.zza(29);
        zzi = a17.b(zzbkVar8.zzb()).a();
        c.b a18 = c.a("onDeviceFaceDetectionLogEvent");
        zzbk zzbkVar9 = new zzbk();
        zzbkVar9.zza(5);
        zzj = a18.b(zzbkVar9.zzb()).a();
        c.b a19 = c.a("onDeviceFaceLoadLogEvent");
        zzbk zzbkVar10 = new zzbk();
        zzbkVar10.zza(59);
        zzk = a19.b(zzbkVar10.zzb()).a();
        c.b a20 = c.a("onDeviceTextDetectionLogEvent");
        zzbk zzbkVar11 = new zzbk();
        zzbkVar11.zza(6);
        zzl = a20.b(zzbkVar11.zzb()).a();
        c.b a21 = c.a("onDeviceTextDetectionLoadLogEvent");
        zzbk zzbkVar12 = new zzbk();
        zzbkVar12.zza(79);
        zzm = a21.b(zzbkVar12.zzb()).a();
        c.b a22 = c.a("onDeviceBarcodeDetectionLogEvent");
        zzbk zzbkVar13 = new zzbk();
        zzbkVar13.zza(7);
        zzn = a22.b(zzbkVar13.zzb()).a();
        c.b a23 = c.a("onDeviceBarcodeLoadLogEvent");
        zzbk zzbkVar14 = new zzbk();
        zzbkVar14.zza(58);
        zzo = a23.b(zzbkVar14.zzb()).a();
        c.b a24 = c.a("onDeviceImageLabelCreateLogEvent");
        zzbk zzbkVar15 = new zzbk();
        zzbkVar15.zza(48);
        zzp = a24.b(zzbkVar15.zzb()).a();
        c.b a25 = c.a("onDeviceImageLabelLoadLogEvent");
        zzbk zzbkVar16 = new zzbk();
        zzbkVar16.zza(49);
        zzq = a25.b(zzbkVar16.zzb()).a();
        c.b a26 = c.a("onDeviceImageLabelDetectionLogEvent");
        zzbk zzbkVar17 = new zzbk();
        zzbkVar17.zza(18);
        zzr = a26.b(zzbkVar17.zzb()).a();
        c.b a27 = c.a("onDeviceObjectCreateLogEvent");
        zzbk zzbkVar18 = new zzbk();
        zzbkVar18.zza(26);
        zzs = a27.b(zzbkVar18.zzb()).a();
        c.b a28 = c.a("onDeviceObjectLoadLogEvent");
        zzbk zzbkVar19 = new zzbk();
        zzbkVar19.zza(27);
        zzt = a28.b(zzbkVar19.zzb()).a();
        c.b a29 = c.a("onDeviceObjectInferenceLogEvent");
        zzbk zzbkVar20 = new zzbk();
        zzbkVar20.zza(28);
        zzu = a29.b(zzbkVar20.zzb()).a();
        c.b a30 = c.a("onDevicePoseDetectionLogEvent");
        zzbk zzbkVar21 = new zzbk();
        zzbkVar21.zza(44);
        zzv = a30.b(zzbkVar21.zzb()).a();
        c.b a31 = c.a("onDeviceSegmentationLogEvent");
        zzbk zzbkVar22 = new zzbk();
        zzbkVar22.zza(45);
        zzw = a31.b(zzbkVar22.zzb()).a();
        c.b a32 = c.a("onDeviceSmartReplyLogEvent");
        zzbk zzbkVar23 = new zzbk();
        zzbkVar23.zza(19);
        zzx = a32.b(zzbkVar23.zzb()).a();
        c.b a33 = c.a("onDeviceLanguageIdentificationLogEvent");
        zzbk zzbkVar24 = new zzbk();
        zzbkVar24.zza(21);
        zzy = a33.b(zzbkVar24.zzb()).a();
        c.b a34 = c.a("onDeviceTranslationLogEvent");
        zzbk zzbkVar25 = new zzbk();
        zzbkVar25.zza(22);
        zzz = a34.b(zzbkVar25.zzb()).a();
        c.b a35 = c.a("cloudFaceDetectionLogEvent");
        zzbk zzbkVar26 = new zzbk();
        zzbkVar26.zza(8);
        zzA = a35.b(zzbkVar26.zzb()).a();
        c.b a36 = c.a("cloudCropHintDetectionLogEvent");
        zzbk zzbkVar27 = new zzbk();
        zzbkVar27.zza(9);
        zzB = a36.b(zzbkVar27.zzb()).a();
        c.b a37 = c.a("cloudDocumentTextDetectionLogEvent");
        zzbk zzbkVar28 = new zzbk();
        zzbkVar28.zza(10);
        zzC = a37.b(zzbkVar28.zzb()).a();
        c.b a38 = c.a("cloudImagePropertiesDetectionLogEvent");
        zzbk zzbkVar29 = new zzbk();
        zzbkVar29.zza(11);
        zzD = a38.b(zzbkVar29.zzb()).a();
        c.b a39 = c.a("cloudImageLabelDetectionLogEvent");
        zzbk zzbkVar30 = new zzbk();
        zzbkVar30.zza(12);
        zzE = a39.b(zzbkVar30.zzb()).a();
        c.b a40 = c.a("cloudLandmarkDetectionLogEvent");
        zzbk zzbkVar31 = new zzbk();
        zzbkVar31.zza(13);
        zzF = a40.b(zzbkVar31.zzb()).a();
        c.b a41 = c.a("cloudLogoDetectionLogEvent");
        zzbk zzbkVar32 = new zzbk();
        zzbkVar32.zza(14);
        zzG = a41.b(zzbkVar32.zzb()).a();
        c.b a42 = c.a("cloudSafeSearchDetectionLogEvent");
        zzbk zzbkVar33 = new zzbk();
        zzbkVar33.zza(15);
        zzH = a42.b(zzbkVar33.zzb()).a();
        c.b a43 = c.a("cloudTextDetectionLogEvent");
        zzbk zzbkVar34 = new zzbk();
        zzbkVar34.zza(16);
        zzI = a43.b(zzbkVar34.zzb()).a();
        c.b a44 = c.a("cloudWebSearchDetectionLogEvent");
        zzbk zzbkVar35 = new zzbk();
        zzbkVar35.zza(17);
        zzJ = a44.b(zzbkVar35.zzb()).a();
        c.b a45 = c.a("automlImageLabelingCreateLogEvent");
        zzbk zzbkVar36 = new zzbk();
        zzbkVar36.zza(23);
        zzK = a45.b(zzbkVar36.zzb()).a();
        c.b a46 = c.a("automlImageLabelingLoadLogEvent");
        zzbk zzbkVar37 = new zzbk();
        zzbkVar37.zza(24);
        zzL = a46.b(zzbkVar37.zzb()).a();
        c.b a47 = c.a("automlImageLabelingInferenceLogEvent");
        zzbk zzbkVar38 = new zzbk();
        zzbkVar38.zza(25);
        zzM = a47.b(zzbkVar38.zzb()).a();
        c.b a48 = c.a("isModelDownloadedLogEvent");
        zzbk zzbkVar39 = new zzbk();
        zzbkVar39.zza(39);
        zzN = a48.b(zzbkVar39.zzb()).a();
        c.b a49 = c.a("deleteModelLogEvent");
        zzbk zzbkVar40 = new zzbk();
        zzbkVar40.zza(40);
        zzO = a49.b(zzbkVar40.zzb()).a();
        c.b a50 = c.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzbk zzbkVar41 = new zzbk();
        zzbkVar41.zza(30);
        zzP = a50.b(zzbkVar41.zzb()).a();
        c.b a51 = c.a("aggregatedCustomModelInferenceLogEvent");
        zzbk zzbkVar42 = new zzbk();
        zzbkVar42.zza(31);
        zzQ = a51.b(zzbkVar42.zzb()).a();
        c.b a52 = c.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzbk zzbkVar43 = new zzbk();
        zzbkVar43.zza(32);
        zzR = a52.b(zzbkVar43.zzb()).a();
        c.b a53 = c.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzbk zzbkVar44 = new zzbk();
        zzbkVar44.zza(33);
        zzS = a53.b(zzbkVar44.zzb()).a();
        c.b a54 = c.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzbk zzbkVar45 = new zzbk();
        zzbkVar45.zza(34);
        zzT = a54.b(zzbkVar45.zzb()).a();
        c.b a55 = c.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzbk zzbkVar46 = new zzbk();
        zzbkVar46.zza(35);
        zzU = a55.b(zzbkVar46.zzb()).a();
        c.b a56 = c.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzbk zzbkVar47 = new zzbk();
        zzbkVar47.zza(36);
        zzV = a56.b(zzbkVar47.zzb()).a();
        c.b a57 = c.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzbk zzbkVar48 = new zzbk();
        zzbkVar48.zza(46);
        zzW = a57.b(zzbkVar48.zzb()).a();
        c.b a58 = c.a("aggregatedOnDeviceSegmentationLogEvent");
        zzbk zzbkVar49 = new zzbk();
        zzbkVar49.zza(47);
        zzX = a58.b(zzbkVar49.zzb()).a();
        c.b a59 = c.a("pipelineAccelerationInferenceEvents");
        zzbk zzbkVar50 = new zzbk();
        zzbkVar50.zza(69);
        zzY = a59.b(zzbkVar50.zzb()).a();
        c.b a60 = c.a("remoteConfigLogEvent");
        zzbk zzbkVar51 = new zzbk();
        zzbkVar51.zza(42);
        zzZ = a60.b(zzbkVar51.zzb()).a();
        c.b a61 = c.a("inputImageConstructionLogEvent");
        zzbk zzbkVar52 = new zzbk();
        zzbkVar52.zza(50);
        zzaa = a61.b(zzbkVar52.zzb()).a();
        c.b a62 = c.a("leakedHandleEvent");
        zzbk zzbkVar53 = new zzbk();
        zzbkVar53.zza(51);
        zzab = a62.b(zzbkVar53.zzb()).a();
        c.b a63 = c.a("cameraSourceLogEvent");
        zzbk zzbkVar54 = new zzbk();
        zzbkVar54.zza(52);
        zzac = a63.b(zzbkVar54.zzb()).a();
        c.b a64 = c.a("imageLabelOptionalModuleLogEvent");
        zzbk zzbkVar55 = new zzbk();
        zzbkVar55.zza(53);
        zzad = a64.b(zzbkVar55.zzb()).a();
        c.b a65 = c.a("languageIdentificationOptionalModuleLogEvent");
        zzbk zzbkVar56 = new zzbk();
        zzbkVar56.zza(54);
        zzae = a65.b(zzbkVar56.zzb()).a();
        c.b a66 = c.a("faceDetectionOptionalModuleLogEvent");
        zzbk zzbkVar57 = new zzbk();
        zzbkVar57.zza(60);
        zzaf = a66.b(zzbkVar57.zzb()).a();
        c.b a67 = c.a("documentDetectionOptionalModuleLogEvent");
        zzbk zzbkVar58 = new zzbk();
        zzbkVar58.zza(85);
        zzag = a67.b(zzbkVar58.zzb()).a();
        c.b a68 = c.a("documentCroppingOptionalModuleLogEvent");
        zzbk zzbkVar59 = new zzbk();
        zzbkVar59.zza(86);
        zzah = a68.b(zzbkVar59.zzb()).a();
        c.b a69 = c.a("documentEnhancementOptionalModuleLogEvent");
        zzbk zzbkVar60 = new zzbk();
        zzbkVar60.zza(87);
        zzai = a69.b(zzbkVar60.zzb()).a();
        c.b a70 = c.a("nlClassifierOptionalModuleLogEvent");
        zzbk zzbkVar61 = new zzbk();
        zzbkVar61.zza(55);
        zzaj = a70.b(zzbkVar61.zzb()).a();
        c.b a71 = c.a("nlClassifierClientLibraryLogEvent");
        zzbk zzbkVar62 = new zzbk();
        zzbkVar62.zza(56);
        zzak = a71.b(zzbkVar62.zzb()).a();
        c.b a72 = c.a("accelerationAllowlistLogEvent");
        zzbk zzbkVar63 = new zzbk();
        zzbkVar63.zza(57);
        zzal = a72.b(zzbkVar63.zzb()).a();
        c.b a73 = c.a("toxicityDetectionCreateEvent");
        zzbk zzbkVar64 = new zzbk();
        zzbkVar64.zza(62);
        zzam = a73.b(zzbkVar64.zzb()).a();
        c.b a74 = c.a("toxicityDetectionLoadEvent");
        zzbk zzbkVar65 = new zzbk();
        zzbkVar65.zza(63);
        zzan = a74.b(zzbkVar65.zzb()).a();
        c.b a75 = c.a("toxicityDetectionInferenceEvent");
        zzbk zzbkVar66 = new zzbk();
        zzbkVar66.zza(64);
        zzao = a75.b(zzbkVar66.zzb()).a();
        c.b a76 = c.a("barcodeDetectionOptionalModuleLogEvent");
        zzbk zzbkVar67 = new zzbk();
        zzbkVar67.zza(65);
        zzap = a76.b(zzbkVar67.zzb()).a();
        c.b a77 = c.a("customImageLabelOptionalModuleLogEvent");
        zzbk zzbkVar68 = new zzbk();
        zzbkVar68.zza(66);
        zzaq = a77.b(zzbkVar68.zzb()).a();
        c.b a78 = c.a("codeScannerScanApiEvent");
        zzbk zzbkVar69 = new zzbk();
        zzbkVar69.zza(67);
        zzar = a78.b(zzbkVar69.zzb()).a();
        c.b a79 = c.a("codeScannerOptionalModuleEvent");
        zzbk zzbkVar70 = new zzbk();
        zzbkVar70.zza(68);
        zzas = a79.b(zzbkVar70.zzb()).a();
        c.b a80 = c.a("onDeviceExplicitContentCreateLogEvent");
        zzbk zzbkVar71 = new zzbk();
        zzbkVar71.zza(70);
        zzat = a80.b(zzbkVar71.zzb()).a();
        c.b a81 = c.a("onDeviceExplicitContentLoadLogEvent");
        zzbk zzbkVar72 = new zzbk();
        zzbkVar72.zza(71);
        zzau = a81.b(zzbkVar72.zzb()).a();
        c.b a82 = c.a("onDeviceExplicitContentInferenceLogEvent");
        zzbk zzbkVar73 = new zzbk();
        zzbkVar73.zza(72);
        zzav = a82.b(zzbkVar73.zzb()).a();
        c.b a83 = c.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzbk zzbkVar74 = new zzbk();
        zzbkVar74.zza(73);
        zzaw = a83.b(zzbkVar74.zzb()).a();
        c.b a84 = c.a("onDeviceFaceMeshCreateLogEvent");
        zzbk zzbkVar75 = new zzbk();
        zzbkVar75.zza(74);
        zzax = a84.b(zzbkVar75.zzb()).a();
        c.b a85 = c.a("onDeviceFaceMeshLoadLogEvent");
        zzbk zzbkVar76 = new zzbk();
        zzbkVar76.zza(75);
        zzay = a85.b(zzbkVar76.zzb()).a();
        c.b a86 = c.a("onDeviceFaceMeshLogEvent");
        zzbk zzbkVar77 = new zzbk();
        zzbkVar77.zza(76);
        zzaz = a86.b(zzbkVar77.zzb()).a();
        c.b a87 = c.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzbk zzbkVar78 = new zzbk();
        zzbkVar78.zza(77);
        zzaA = a87.b(zzbkVar78.zzb()).a();
        c.b a88 = c.a("smartReplyOptionalModuleLogEvent");
        zzbk zzbkVar79 = new zzbk();
        zzbkVar79.zza(78);
        zzaB = a88.b(zzbkVar79.zzb()).a();
        c.b a89 = c.a("textDetectionOptionalModuleLogEvent");
        zzbk zzbkVar80 = new zzbk();
        zzbkVar80.zza(80);
        zzaC = a89.b(zzbkVar80.zzb()).a();
        c.b a90 = c.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzbk zzbkVar81 = new zzbk();
        zzbkVar81.zza(81);
        zzaD = a90.b(zzbkVar81.zzb()).a();
        c.b a91 = c.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzbk zzbkVar82 = new zzbk();
        zzbkVar82.zza(82);
        zzaE = a91.b(zzbkVar82.zzb()).a();
        c.b a92 = c.a("onDeviceImageQualityAnalysisLogEvent");
        zzbk zzbkVar83 = new zzbk();
        zzbkVar83.zza(83);
        zzaF = a92.b(zzbkVar83.zzb()).a();
        c.b a93 = c.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzbk zzbkVar84 = new zzbk();
        zzbkVar84.zza(84);
        zzaG = a93.b(zzbkVar84.zzb()).a();
        c.b a94 = c.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzbk zzbkVar85 = new zzbk();
        zzbkVar85.zza(88);
        zzaH = a94.b(zzbkVar85.zzb()).a();
        c.b a95 = c.a("imageCaptioningOptionalModuleLogEvent");
        zzbk zzbkVar86 = new zzbk();
        zzbkVar86.zza(89);
        zzaI = a95.b(zzbkVar86.zzb()).a();
        c.b a96 = c.a("onDeviceImageCaptioningCreateLogEvent");
        zzbk zzbkVar87 = new zzbk();
        zzbkVar87.zza(90);
        zzaJ = a96.b(zzbkVar87.zzb()).a();
        c.b a97 = c.a("onDeviceImageCaptioningLoadLogEvent");
        zzbk zzbkVar88 = new zzbk();
        zzbkVar88.zza(91);
        zzaK = a97.b(zzbkVar88.zzb()).a();
        c.b a98 = c.a("onDeviceImageCaptioningInferenceLogEvent");
        zzbk zzbkVar89 = new zzbk();
        zzbkVar89.zza(92);
        zzaL = a98.b(zzbkVar89.zzb()).a();
        c.b a99 = c.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzbk zzbkVar90 = new zzbk();
        zzbkVar90.zza(93);
        zzaM = a99.b(zzbkVar90.zzb()).a();
        c.b a100 = c.a("onDeviceDocumentDetectionCreateLogEvent");
        zzbk zzbkVar91 = new zzbk();
        zzbkVar91.zza(94);
        zzaN = a100.b(zzbkVar91.zzb()).a();
        c.b a101 = c.a("onDeviceDocumentDetectionLoadLogEvent");
        zzbk zzbkVar92 = new zzbk();
        zzbkVar92.zza(95);
        zzaO = a101.b(zzbkVar92.zzb()).a();
        c.b a102 = c.a("onDeviceDocumentDetectionLogEvent");
        zzbk zzbkVar93 = new zzbk();
        zzbkVar93.zza(96);
        zzaP = a102.b(zzbkVar93.zzb()).a();
        c.b a103 = c.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzbk zzbkVar94 = new zzbk();
        zzbkVar94.zza(97);
        zzaQ = a103.b(zzbkVar94.zzb()).a();
        c.b a104 = c.a("onDeviceDocumentCroppingCreateLogEvent");
        zzbk zzbkVar95 = new zzbk();
        zzbkVar95.zza(98);
        zzaR = a104.b(zzbkVar95.zzb()).a();
        c.b a105 = c.a("onDeviceDocumentCroppingLoadLogEvent");
        zzbk zzbkVar96 = new zzbk();
        zzbkVar96.zza(99);
        zzaS = a105.b(zzbkVar96.zzb()).a();
        c.b a106 = c.a("onDeviceDocumentCroppingLogEvent");
        zzbk zzbkVar97 = new zzbk();
        zzbkVar97.zza(100);
        zzaT = a106.b(zzbkVar97.zzb()).a();
        c.b a107 = c.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzbk zzbkVar98 = new zzbk();
        zzbkVar98.zza(101);
        zzaU = a107.b(zzbkVar98.zzb()).a();
        c.b a108 = c.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzbk zzbkVar99 = new zzbk();
        zzbkVar99.zza(102);
        zzaV = a108.b(zzbkVar99.zzb()).a();
        c.b a109 = c.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzbk zzbkVar100 = new zzbk();
        zzbkVar100.zza(103);
        zzaW = a109.b(zzbkVar100.zzb()).a();
        c.b a110 = c.a("onDeviceDocumentEnhancementLogEvent");
        zzbk zzbkVar101 = new zzbk();
        zzbkVar101.zza(104);
        zzaX = a110.b(zzbkVar101.zzb()).a();
        c.b a111 = c.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzbk zzbkVar102 = new zzbk();
        zzbkVar102.zza(105);
        zzaY = a111.b(zzbkVar102.zzb()).a();
        c.b a112 = c.a("scannerAutoZoomEvent");
        zzbk zzbkVar103 = new zzbk();
        zzbkVar103.zza(106);
        zzaZ = a112.b(zzbkVar103.zzb()).a();
        c.b a113 = c.a("lowLightAutoExposureComputationEvent");
        zzbk zzbkVar104 = new zzbk();
        zzbkVar104.zza(107);
        zzba = a113.b(zzbkVar104.zzb()).a();
        c.b a114 = c.a("lowLightFrameProcessEvent");
        zzbk zzbkVar105 = new zzbk();
        zzbkVar105.zza(108);
        zzbb = a114.b(zzbkVar105.zzb()).a();
        c.b a115 = c.a("lowLightSceneDetectionEvent");
        zzbk zzbkVar106 = new zzbk();
        zzbkVar106.zza(109);
        zzbc = a115.b(zzbkVar106.zzb()).a();
    }

    private zzgl() {
    }

    @Override // jd.d
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzlq zzlqVar = (zzlq) obj;
        e eVar = (e) obj2;
        eVar.add(zzb, zzlqVar.zzf());
        eVar.add(zzc, zzlqVar.zzd());
        eVar.add(zzd, (Object) null);
        eVar.add(zze, (Object) null);
        eVar.add(zzf, zzlqVar.zze());
        eVar.add(zzg, (Object) null);
        eVar.add(zzh, (Object) null);
        eVar.add(zzi, (Object) null);
        eVar.add(zzj, (Object) null);
        eVar.add(zzk, (Object) null);
        eVar.add(zzl, (Object) null);
        eVar.add(zzm, (Object) null);
        eVar.add(zzn, (Object) null);
        eVar.add(zzo, (Object) null);
        eVar.add(zzp, (Object) null);
        eVar.add(zzq, (Object) null);
        eVar.add(zzr, (Object) null);
        eVar.add(zzs, (Object) null);
        eVar.add(zzt, (Object) null);
        eVar.add(zzu, (Object) null);
        eVar.add(zzv, (Object) null);
        eVar.add(zzw, (Object) null);
        eVar.add(zzx, (Object) null);
        eVar.add(zzy, (Object) null);
        eVar.add(zzz, (Object) null);
        eVar.add(zzA, (Object) null);
        eVar.add(zzB, (Object) null);
        eVar.add(zzC, (Object) null);
        eVar.add(zzD, (Object) null);
        eVar.add(zzE, (Object) null);
        eVar.add(zzF, (Object) null);
        eVar.add(zzG, (Object) null);
        eVar.add(zzH, (Object) null);
        eVar.add(zzI, (Object) null);
        eVar.add(zzJ, (Object) null);
        eVar.add(zzK, (Object) null);
        eVar.add(zzL, (Object) null);
        eVar.add(zzM, (Object) null);
        eVar.add(zzN, zzlqVar.zzb());
        eVar.add(zzO, zzlqVar.zza());
        eVar.add(zzP, (Object) null);
        eVar.add(zzQ, (Object) null);
        eVar.add(zzR, (Object) null);
        eVar.add(zzS, (Object) null);
        eVar.add(zzT, (Object) null);
        eVar.add(zzU, (Object) null);
        eVar.add(zzV, (Object) null);
        eVar.add(zzW, (Object) null);
        eVar.add(zzX, (Object) null);
        eVar.add(zzY, (Object) null);
        eVar.add(zzZ, (Object) null);
        eVar.add(zzaa, (Object) null);
        eVar.add(zzab, zzlqVar.zzc());
        eVar.add(zzac, (Object) null);
        eVar.add(zzad, (Object) null);
        eVar.add(zzae, (Object) null);
        eVar.add(zzaf, (Object) null);
        eVar.add(zzag, (Object) null);
        eVar.add(zzah, (Object) null);
        eVar.add(zzai, (Object) null);
        eVar.add(zzaj, (Object) null);
        eVar.add(zzak, (Object) null);
        eVar.add(zzal, (Object) null);
        eVar.add(zzam, (Object) null);
        eVar.add(zzan, (Object) null);
        eVar.add(zzao, (Object) null);
        eVar.add(zzap, (Object) null);
        eVar.add(zzaq, (Object) null);
        eVar.add(zzar, (Object) null);
        eVar.add(zzas, (Object) null);
        eVar.add(zzat, (Object) null);
        eVar.add(zzau, (Object) null);
        eVar.add(zzav, (Object) null);
        eVar.add(zzaw, (Object) null);
        eVar.add(zzax, (Object) null);
        eVar.add(zzay, (Object) null);
        eVar.add(zzaz, (Object) null);
        eVar.add(zzaA, (Object) null);
        eVar.add(zzaB, (Object) null);
        eVar.add(zzaC, (Object) null);
        eVar.add(zzaD, (Object) null);
        eVar.add(zzaE, (Object) null);
        eVar.add(zzaF, (Object) null);
        eVar.add(zzaG, (Object) null);
        eVar.add(zzaH, (Object) null);
        eVar.add(zzaI, (Object) null);
        eVar.add(zzaJ, (Object) null);
        eVar.add(zzaK, (Object) null);
        eVar.add(zzaL, (Object) null);
        eVar.add(zzaM, (Object) null);
        eVar.add(zzaN, (Object) null);
        eVar.add(zzaO, (Object) null);
        eVar.add(zzaP, (Object) null);
        eVar.add(zzaQ, (Object) null);
        eVar.add(zzaR, (Object) null);
        eVar.add(zzaS, (Object) null);
        eVar.add(zzaT, (Object) null);
        eVar.add(zzaU, (Object) null);
        eVar.add(zzaV, (Object) null);
        eVar.add(zzaW, (Object) null);
        eVar.add(zzaX, (Object) null);
        eVar.add(zzaY, (Object) null);
        eVar.add(zzaZ, (Object) null);
        eVar.add(zzba, (Object) null);
        eVar.add(zzbb, (Object) null);
        eVar.add(zzbc, (Object) null);
    }
}
