package com.google.android.gms.internal.mlkit_vision_barcode;

import io.flutter.plugins.firebase.analytics.Constants;
import jd.c;
import jd.d;
import jd.e;

/* loaded from: classes2.dex */
final class zzkh implements d {
    private static final c zzA;
    private static final c zzB;
    private static final c zzC;
    private static final c zzD;
    private static final c zzE;
    private static final c zzF;
    private static final c zzG;
    private static final c zzH;
    private static final c zzI;
    private static final c zzJ;
    private static final c zzK;
    private static final c zzL;
    private static final c zzM;
    private static final c zzN;
    private static final c zzO;
    private static final c zzP;
    private static final c zzQ;
    private static final c zzR;
    private static final c zzS;
    private static final c zzT;
    private static final c zzU;
    private static final c zzV;
    private static final c zzW;
    private static final c zzX;
    private static final c zzY;
    private static final c zzZ;
    static final zzkh zza = new zzkh();
    private static final c zzaA;
    private static final c zzaB;
    private static final c zzaC;
    private static final c zzaD;
    private static final c zzaE;
    private static final c zzaF;
    private static final c zzaG;
    private static final c zzaH;
    private static final c zzaI;
    private static final c zzaJ;
    private static final c zzaK;
    private static final c zzaL;
    private static final c zzaM;
    private static final c zzaN;
    private static final c zzaO;
    private static final c zzaP;
    private static final c zzaQ;
    private static final c zzaR;
    private static final c zzaS;
    private static final c zzaT;
    private static final c zzaU;
    private static final c zzaV;
    private static final c zzaW;
    private static final c zzaX;
    private static final c zzaY;
    private static final c zzaZ;
    private static final c zzaa;
    private static final c zzab;
    private static final c zzac;
    private static final c zzad;
    private static final c zzae;
    private static final c zzaf;
    private static final c zzag;
    private static final c zzah;
    private static final c zzai;
    private static final c zzaj;
    private static final c zzak;
    private static final c zzal;
    private static final c zzam;
    private static final c zzan;
    private static final c zzao;
    private static final c zzap;
    private static final c zzaq;
    private static final c zzar;
    private static final c zzas;
    private static final c zzat;
    private static final c zzau;
    private static final c zzav;
    private static final c zzaw;
    private static final c zzax;
    private static final c zzay;
    private static final c zzaz;
    private static final c zzb;
    private static final c zzba;
    private static final c zzbb;
    private static final c zzbc;
    private static final c zzc;
    private static final c zzd;
    private static final c zze;
    private static final c zzf;
    private static final c zzg;
    private static final c zzh;
    private static final c zzi;
    private static final c zzj;
    private static final c zzk;
    private static final c zzl;
    private static final c zzm;
    private static final c zzn;
    private static final c zzo;
    private static final c zzp;
    private static final c zzq;
    private static final c zzr;
    private static final c zzs;
    private static final c zzt;
    private static final c zzu;
    private static final c zzv;
    private static final c zzw;
    private static final c zzx;
    private static final c zzy;
    private static final c zzz;

    static {
        c.b a10 = c.a("systemInfo");
        zzfc zzfcVar = new zzfc();
        zzfcVar.zza(1);
        zzb = a10.b(zzfcVar.zzb()).a();
        c.b a11 = c.a(Constants.EVENT_NAME);
        zzfc zzfcVar2 = new zzfc();
        zzfcVar2.zza(2);
        zzc = a11.b(zzfcVar2.zzb()).a();
        c.b a12 = c.a("isThickClient");
        zzfc zzfcVar3 = new zzfc();
        zzfcVar3.zza(37);
        zzd = a12.b(zzfcVar3.zzb()).a();
        c.b a13 = c.a("clientType");
        zzfc zzfcVar4 = new zzfc();
        zzfcVar4.zza(61);
        zze = a13.b(zzfcVar4.zzb()).a();
        c.b a14 = c.a("modelDownloadLogEvent");
        zzfc zzfcVar5 = new zzfc();
        zzfcVar5.zza(3);
        zzf = a14.b(zzfcVar5.zzb()).a();
        c.b a15 = c.a("customModelLoadLogEvent");
        zzfc zzfcVar6 = new zzfc();
        zzfcVar6.zza(20);
        zzg = a15.b(zzfcVar6.zzb()).a();
        c.b a16 = c.a("customModelInferenceLogEvent");
        zzfc zzfcVar7 = new zzfc();
        zzfcVar7.zza(4);
        zzh = a16.b(zzfcVar7.zzb()).a();
        c.b a17 = c.a("customModelCreateLogEvent");
        zzfc zzfcVar8 = new zzfc();
        zzfcVar8.zza(29);
        zzi = a17.b(zzfcVar8.zzb()).a();
        c.b a18 = c.a("onDeviceFaceDetectionLogEvent");
        zzfc zzfcVar9 = new zzfc();
        zzfcVar9.zza(5);
        zzj = a18.b(zzfcVar9.zzb()).a();
        c.b a19 = c.a("onDeviceFaceLoadLogEvent");
        zzfc zzfcVar10 = new zzfc();
        zzfcVar10.zza(59);
        zzk = a19.b(zzfcVar10.zzb()).a();
        c.b a20 = c.a("onDeviceTextDetectionLogEvent");
        zzfc zzfcVar11 = new zzfc();
        zzfcVar11.zza(6);
        zzl = a20.b(zzfcVar11.zzb()).a();
        c.b a21 = c.a("onDeviceTextDetectionLoadLogEvent");
        zzfc zzfcVar12 = new zzfc();
        zzfcVar12.zza(79);
        zzm = a21.b(zzfcVar12.zzb()).a();
        c.b a22 = c.a("onDeviceBarcodeDetectionLogEvent");
        zzfc zzfcVar13 = new zzfc();
        zzfcVar13.zza(7);
        zzn = a22.b(zzfcVar13.zzb()).a();
        c.b a23 = c.a("onDeviceBarcodeLoadLogEvent");
        zzfc zzfcVar14 = new zzfc();
        zzfcVar14.zza(58);
        zzo = a23.b(zzfcVar14.zzb()).a();
        c.b a24 = c.a("onDeviceImageLabelCreateLogEvent");
        zzfc zzfcVar15 = new zzfc();
        zzfcVar15.zza(48);
        zzp = a24.b(zzfcVar15.zzb()).a();
        c.b a25 = c.a("onDeviceImageLabelLoadLogEvent");
        zzfc zzfcVar16 = new zzfc();
        zzfcVar16.zza(49);
        zzq = a25.b(zzfcVar16.zzb()).a();
        c.b a26 = c.a("onDeviceImageLabelDetectionLogEvent");
        zzfc zzfcVar17 = new zzfc();
        zzfcVar17.zza(18);
        zzr = a26.b(zzfcVar17.zzb()).a();
        c.b a27 = c.a("onDeviceObjectCreateLogEvent");
        zzfc zzfcVar18 = new zzfc();
        zzfcVar18.zza(26);
        zzs = a27.b(zzfcVar18.zzb()).a();
        c.b a28 = c.a("onDeviceObjectLoadLogEvent");
        zzfc zzfcVar19 = new zzfc();
        zzfcVar19.zza(27);
        zzt = a28.b(zzfcVar19.zzb()).a();
        c.b a29 = c.a("onDeviceObjectInferenceLogEvent");
        zzfc zzfcVar20 = new zzfc();
        zzfcVar20.zza(28);
        zzu = a29.b(zzfcVar20.zzb()).a();
        c.b a30 = c.a("onDevicePoseDetectionLogEvent");
        zzfc zzfcVar21 = new zzfc();
        zzfcVar21.zza(44);
        zzv = a30.b(zzfcVar21.zzb()).a();
        c.b a31 = c.a("onDeviceSegmentationLogEvent");
        zzfc zzfcVar22 = new zzfc();
        zzfcVar22.zza(45);
        zzw = a31.b(zzfcVar22.zzb()).a();
        c.b a32 = c.a("onDeviceSmartReplyLogEvent");
        zzfc zzfcVar23 = new zzfc();
        zzfcVar23.zza(19);
        zzx = a32.b(zzfcVar23.zzb()).a();
        c.b a33 = c.a("onDeviceLanguageIdentificationLogEvent");
        zzfc zzfcVar24 = new zzfc();
        zzfcVar24.zza(21);
        zzy = a33.b(zzfcVar24.zzb()).a();
        c.b a34 = c.a("onDeviceTranslationLogEvent");
        zzfc zzfcVar25 = new zzfc();
        zzfcVar25.zza(22);
        zzz = a34.b(zzfcVar25.zzb()).a();
        c.b a35 = c.a("cloudFaceDetectionLogEvent");
        zzfc zzfcVar26 = new zzfc();
        zzfcVar26.zza(8);
        zzA = a35.b(zzfcVar26.zzb()).a();
        c.b a36 = c.a("cloudCropHintDetectionLogEvent");
        zzfc zzfcVar27 = new zzfc();
        zzfcVar27.zza(9);
        zzB = a36.b(zzfcVar27.zzb()).a();
        c.b a37 = c.a("cloudDocumentTextDetectionLogEvent");
        zzfc zzfcVar28 = new zzfc();
        zzfcVar28.zza(10);
        zzC = a37.b(zzfcVar28.zzb()).a();
        c.b a38 = c.a("cloudImagePropertiesDetectionLogEvent");
        zzfc zzfcVar29 = new zzfc();
        zzfcVar29.zza(11);
        zzD = a38.b(zzfcVar29.zzb()).a();
        c.b a39 = c.a("cloudImageLabelDetectionLogEvent");
        zzfc zzfcVar30 = new zzfc();
        zzfcVar30.zza(12);
        zzE = a39.b(zzfcVar30.zzb()).a();
        c.b a40 = c.a("cloudLandmarkDetectionLogEvent");
        zzfc zzfcVar31 = new zzfc();
        zzfcVar31.zza(13);
        zzF = a40.b(zzfcVar31.zzb()).a();
        c.b a41 = c.a("cloudLogoDetectionLogEvent");
        zzfc zzfcVar32 = new zzfc();
        zzfcVar32.zza(14);
        zzG = a41.b(zzfcVar32.zzb()).a();
        c.b a42 = c.a("cloudSafeSearchDetectionLogEvent");
        zzfc zzfcVar33 = new zzfc();
        zzfcVar33.zza(15);
        zzH = a42.b(zzfcVar33.zzb()).a();
        c.b a43 = c.a("cloudTextDetectionLogEvent");
        zzfc zzfcVar34 = new zzfc();
        zzfcVar34.zza(16);
        zzI = a43.b(zzfcVar34.zzb()).a();
        c.b a44 = c.a("cloudWebSearchDetectionLogEvent");
        zzfc zzfcVar35 = new zzfc();
        zzfcVar35.zza(17);
        zzJ = a44.b(zzfcVar35.zzb()).a();
        c.b a45 = c.a("automlImageLabelingCreateLogEvent");
        zzfc zzfcVar36 = new zzfc();
        zzfcVar36.zza(23);
        zzK = a45.b(zzfcVar36.zzb()).a();
        c.b a46 = c.a("automlImageLabelingLoadLogEvent");
        zzfc zzfcVar37 = new zzfc();
        zzfcVar37.zza(24);
        zzL = a46.b(zzfcVar37.zzb()).a();
        c.b a47 = c.a("automlImageLabelingInferenceLogEvent");
        zzfc zzfcVar38 = new zzfc();
        zzfcVar38.zza(25);
        zzM = a47.b(zzfcVar38.zzb()).a();
        c.b a48 = c.a("isModelDownloadedLogEvent");
        zzfc zzfcVar39 = new zzfc();
        zzfcVar39.zza(39);
        zzN = a48.b(zzfcVar39.zzb()).a();
        c.b a49 = c.a("deleteModelLogEvent");
        zzfc zzfcVar40 = new zzfc();
        zzfcVar40.zza(40);
        zzO = a49.b(zzfcVar40.zzb()).a();
        c.b a50 = c.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzfc zzfcVar41 = new zzfc();
        zzfcVar41.zza(30);
        zzP = a50.b(zzfcVar41.zzb()).a();
        c.b a51 = c.a("aggregatedCustomModelInferenceLogEvent");
        zzfc zzfcVar42 = new zzfc();
        zzfcVar42.zza(31);
        zzQ = a51.b(zzfcVar42.zzb()).a();
        c.b a52 = c.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzfc zzfcVar43 = new zzfc();
        zzfcVar43.zza(32);
        zzR = a52.b(zzfcVar43.zzb()).a();
        c.b a53 = c.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzfc zzfcVar44 = new zzfc();
        zzfcVar44.zza(33);
        zzS = a53.b(zzfcVar44.zzb()).a();
        c.b a54 = c.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzfc zzfcVar45 = new zzfc();
        zzfcVar45.zza(34);
        zzT = a54.b(zzfcVar45.zzb()).a();
        c.b a55 = c.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzfc zzfcVar46 = new zzfc();
        zzfcVar46.zza(35);
        zzU = a55.b(zzfcVar46.zzb()).a();
        c.b a56 = c.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzfc zzfcVar47 = new zzfc();
        zzfcVar47.zza(36);
        zzV = a56.b(zzfcVar47.zzb()).a();
        c.b a57 = c.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzfc zzfcVar48 = new zzfc();
        zzfcVar48.zza(46);
        zzW = a57.b(zzfcVar48.zzb()).a();
        c.b a58 = c.a("aggregatedOnDeviceSegmentationLogEvent");
        zzfc zzfcVar49 = new zzfc();
        zzfcVar49.zza(47);
        zzX = a58.b(zzfcVar49.zzb()).a();
        c.b a59 = c.a("pipelineAccelerationInferenceEvents");
        zzfc zzfcVar50 = new zzfc();
        zzfcVar50.zza(69);
        zzY = a59.b(zzfcVar50.zzb()).a();
        c.b a60 = c.a("remoteConfigLogEvent");
        zzfc zzfcVar51 = new zzfc();
        zzfcVar51.zza(42);
        zzZ = a60.b(zzfcVar51.zzb()).a();
        c.b a61 = c.a("inputImageConstructionLogEvent");
        zzfc zzfcVar52 = new zzfc();
        zzfcVar52.zza(50);
        zzaa = a61.b(zzfcVar52.zzb()).a();
        c.b a62 = c.a("leakedHandleEvent");
        zzfc zzfcVar53 = new zzfc();
        zzfcVar53.zza(51);
        zzab = a62.b(zzfcVar53.zzb()).a();
        c.b a63 = c.a("cameraSourceLogEvent");
        zzfc zzfcVar54 = new zzfc();
        zzfcVar54.zza(52);
        zzac = a63.b(zzfcVar54.zzb()).a();
        c.b a64 = c.a("imageLabelOptionalModuleLogEvent");
        zzfc zzfcVar55 = new zzfc();
        zzfcVar55.zza(53);
        zzad = a64.b(zzfcVar55.zzb()).a();
        c.b a65 = c.a("languageIdentificationOptionalModuleLogEvent");
        zzfc zzfcVar56 = new zzfc();
        zzfcVar56.zza(54);
        zzae = a65.b(zzfcVar56.zzb()).a();
        c.b a66 = c.a("faceDetectionOptionalModuleLogEvent");
        zzfc zzfcVar57 = new zzfc();
        zzfcVar57.zza(60);
        zzaf = a66.b(zzfcVar57.zzb()).a();
        c.b a67 = c.a("documentDetectionOptionalModuleLogEvent");
        zzfc zzfcVar58 = new zzfc();
        zzfcVar58.zza(85);
        zzag = a67.b(zzfcVar58.zzb()).a();
        c.b a68 = c.a("documentCroppingOptionalModuleLogEvent");
        zzfc zzfcVar59 = new zzfc();
        zzfcVar59.zza(86);
        zzah = a68.b(zzfcVar59.zzb()).a();
        c.b a69 = c.a("documentEnhancementOptionalModuleLogEvent");
        zzfc zzfcVar60 = new zzfc();
        zzfcVar60.zza(87);
        zzai = a69.b(zzfcVar60.zzb()).a();
        c.b a70 = c.a("nlClassifierOptionalModuleLogEvent");
        zzfc zzfcVar61 = new zzfc();
        zzfcVar61.zza(55);
        zzaj = a70.b(zzfcVar61.zzb()).a();
        c.b a71 = c.a("nlClassifierClientLibraryLogEvent");
        zzfc zzfcVar62 = new zzfc();
        zzfcVar62.zza(56);
        zzak = a71.b(zzfcVar62.zzb()).a();
        c.b a72 = c.a("accelerationAllowlistLogEvent");
        zzfc zzfcVar63 = new zzfc();
        zzfcVar63.zza(57);
        zzal = a72.b(zzfcVar63.zzb()).a();
        c.b a73 = c.a("toxicityDetectionCreateEvent");
        zzfc zzfcVar64 = new zzfc();
        zzfcVar64.zza(62);
        zzam = a73.b(zzfcVar64.zzb()).a();
        c.b a74 = c.a("toxicityDetectionLoadEvent");
        zzfc zzfcVar65 = new zzfc();
        zzfcVar65.zza(63);
        zzan = a74.b(zzfcVar65.zzb()).a();
        c.b a75 = c.a("toxicityDetectionInferenceEvent");
        zzfc zzfcVar66 = new zzfc();
        zzfcVar66.zza(64);
        zzao = a75.b(zzfcVar66.zzb()).a();
        c.b a76 = c.a("barcodeDetectionOptionalModuleLogEvent");
        zzfc zzfcVar67 = new zzfc();
        zzfcVar67.zza(65);
        zzap = a76.b(zzfcVar67.zzb()).a();
        c.b a77 = c.a("customImageLabelOptionalModuleLogEvent");
        zzfc zzfcVar68 = new zzfc();
        zzfcVar68.zza(66);
        zzaq = a77.b(zzfcVar68.zzb()).a();
        c.b a78 = c.a("codeScannerScanApiEvent");
        zzfc zzfcVar69 = new zzfc();
        zzfcVar69.zza(67);
        zzar = a78.b(zzfcVar69.zzb()).a();
        c.b a79 = c.a("codeScannerOptionalModuleEvent");
        zzfc zzfcVar70 = new zzfc();
        zzfcVar70.zza(68);
        zzas = a79.b(zzfcVar70.zzb()).a();
        c.b a80 = c.a("onDeviceExplicitContentCreateLogEvent");
        zzfc zzfcVar71 = new zzfc();
        zzfcVar71.zza(70);
        zzat = a80.b(zzfcVar71.zzb()).a();
        c.b a81 = c.a("onDeviceExplicitContentLoadLogEvent");
        zzfc zzfcVar72 = new zzfc();
        zzfcVar72.zza(71);
        zzau = a81.b(zzfcVar72.zzb()).a();
        c.b a82 = c.a("onDeviceExplicitContentInferenceLogEvent");
        zzfc zzfcVar73 = new zzfc();
        zzfcVar73.zza(72);
        zzav = a82.b(zzfcVar73.zzb()).a();
        c.b a83 = c.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzfc zzfcVar74 = new zzfc();
        zzfcVar74.zza(73);
        zzaw = a83.b(zzfcVar74.zzb()).a();
        c.b a84 = c.a("onDeviceFaceMeshCreateLogEvent");
        zzfc zzfcVar75 = new zzfc();
        zzfcVar75.zza(74);
        zzax = a84.b(zzfcVar75.zzb()).a();
        c.b a85 = c.a("onDeviceFaceMeshLoadLogEvent");
        zzfc zzfcVar76 = new zzfc();
        zzfcVar76.zza(75);
        zzay = a85.b(zzfcVar76.zzb()).a();
        c.b a86 = c.a("onDeviceFaceMeshLogEvent");
        zzfc zzfcVar77 = new zzfc();
        zzfcVar77.zza(76);
        zzaz = a86.b(zzfcVar77.zzb()).a();
        c.b a87 = c.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzfc zzfcVar78 = new zzfc();
        zzfcVar78.zza(77);
        zzaA = a87.b(zzfcVar78.zzb()).a();
        c.b a88 = c.a("smartReplyOptionalModuleLogEvent");
        zzfc zzfcVar79 = new zzfc();
        zzfcVar79.zza(78);
        zzaB = a88.b(zzfcVar79.zzb()).a();
        c.b a89 = c.a("textDetectionOptionalModuleLogEvent");
        zzfc zzfcVar80 = new zzfc();
        zzfcVar80.zza(80);
        zzaC = a89.b(zzfcVar80.zzb()).a();
        c.b a90 = c.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzfc zzfcVar81 = new zzfc();
        zzfcVar81.zza(81);
        zzaD = a90.b(zzfcVar81.zzb()).a();
        c.b a91 = c.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzfc zzfcVar82 = new zzfc();
        zzfcVar82.zza(82);
        zzaE = a91.b(zzfcVar82.zzb()).a();
        c.b a92 = c.a("onDeviceImageQualityAnalysisLogEvent");
        zzfc zzfcVar83 = new zzfc();
        zzfcVar83.zza(83);
        zzaF = a92.b(zzfcVar83.zzb()).a();
        c.b a93 = c.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzfc zzfcVar84 = new zzfc();
        zzfcVar84.zza(84);
        zzaG = a93.b(zzfcVar84.zzb()).a();
        c.b a94 = c.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzfc zzfcVar85 = new zzfc();
        zzfcVar85.zza(88);
        zzaH = a94.b(zzfcVar85.zzb()).a();
        c.b a95 = c.a("imageCaptioningOptionalModuleLogEvent");
        zzfc zzfcVar86 = new zzfc();
        zzfcVar86.zza(89);
        zzaI = a95.b(zzfcVar86.zzb()).a();
        c.b a96 = c.a("onDeviceImageCaptioningCreateLogEvent");
        zzfc zzfcVar87 = new zzfc();
        zzfcVar87.zza(90);
        zzaJ = a96.b(zzfcVar87.zzb()).a();
        c.b a97 = c.a("onDeviceImageCaptioningLoadLogEvent");
        zzfc zzfcVar88 = new zzfc();
        zzfcVar88.zza(91);
        zzaK = a97.b(zzfcVar88.zzb()).a();
        c.b a98 = c.a("onDeviceImageCaptioningInferenceLogEvent");
        zzfc zzfcVar89 = new zzfc();
        zzfcVar89.zza(92);
        zzaL = a98.b(zzfcVar89.zzb()).a();
        c.b a99 = c.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzfc zzfcVar90 = new zzfc();
        zzfcVar90.zza(93);
        zzaM = a99.b(zzfcVar90.zzb()).a();
        c.b a100 = c.a("onDeviceDocumentDetectionCreateLogEvent");
        zzfc zzfcVar91 = new zzfc();
        zzfcVar91.zza(94);
        zzaN = a100.b(zzfcVar91.zzb()).a();
        c.b a101 = c.a("onDeviceDocumentDetectionLoadLogEvent");
        zzfc zzfcVar92 = new zzfc();
        zzfcVar92.zza(95);
        zzaO = a101.b(zzfcVar92.zzb()).a();
        c.b a102 = c.a("onDeviceDocumentDetectionLogEvent");
        zzfc zzfcVar93 = new zzfc();
        zzfcVar93.zza(96);
        zzaP = a102.b(zzfcVar93.zzb()).a();
        c.b a103 = c.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzfc zzfcVar94 = new zzfc();
        zzfcVar94.zza(97);
        zzaQ = a103.b(zzfcVar94.zzb()).a();
        c.b a104 = c.a("onDeviceDocumentCroppingCreateLogEvent");
        zzfc zzfcVar95 = new zzfc();
        zzfcVar95.zza(98);
        zzaR = a104.b(zzfcVar95.zzb()).a();
        c.b a105 = c.a("onDeviceDocumentCroppingLoadLogEvent");
        zzfc zzfcVar96 = new zzfc();
        zzfcVar96.zza(99);
        zzaS = a105.b(zzfcVar96.zzb()).a();
        c.b a106 = c.a("onDeviceDocumentCroppingLogEvent");
        zzfc zzfcVar97 = new zzfc();
        zzfcVar97.zza(100);
        zzaT = a106.b(zzfcVar97.zzb()).a();
        c.b a107 = c.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzfc zzfcVar98 = new zzfc();
        zzfcVar98.zza(101);
        zzaU = a107.b(zzfcVar98.zzb()).a();
        c.b a108 = c.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzfc zzfcVar99 = new zzfc();
        zzfcVar99.zza(102);
        zzaV = a108.b(zzfcVar99.zzb()).a();
        c.b a109 = c.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzfc zzfcVar100 = new zzfc();
        zzfcVar100.zza(103);
        zzaW = a109.b(zzfcVar100.zzb()).a();
        c.b a110 = c.a("onDeviceDocumentEnhancementLogEvent");
        zzfc zzfcVar101 = new zzfc();
        zzfcVar101.zza(104);
        zzaX = a110.b(zzfcVar101.zzb()).a();
        c.b a111 = c.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzfc zzfcVar102 = new zzfc();
        zzfcVar102.zza(105);
        zzaY = a111.b(zzfcVar102.zzb()).a();
        c.b a112 = c.a("scannerAutoZoomEvent");
        zzfc zzfcVar103 = new zzfc();
        zzfcVar103.zza(106);
        zzaZ = a112.b(zzfcVar103.zzb()).a();
        c.b a113 = c.a("lowLightAutoExposureComputationEvent");
        zzfc zzfcVar104 = new zzfc();
        zzfcVar104.zza(107);
        zzba = a113.b(zzfcVar104.zzb()).a();
        c.b a114 = c.a("lowLightFrameProcessEvent");
        zzfc zzfcVar105 = new zzfc();
        zzfcVar105.zza(108);
        zzbb = a114.b(zzfcVar105.zzb()).a();
        c.b a115 = c.a("lowLightSceneDetectionEvent");
        zzfc zzfcVar106 = new zzfc();
        zzfcVar106.zza(109);
        zzbc = a115.b(zzfcVar106.zzb()).a();
    }

    private zzkh() {
    }

    @Override // jd.d
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzpn zzpnVar = (zzpn) obj;
        e eVar = (e) obj2;
        eVar.add(zzb, zzpnVar.zzg());
        eVar.add(zzc, zzpnVar.zzc());
        eVar.add(zzd, (Object) null);
        eVar.add(zze, zzpnVar.zzb());
        eVar.add(zzf, (Object) null);
        eVar.add(zzg, (Object) null);
        eVar.add(zzh, (Object) null);
        eVar.add(zzi, (Object) null);
        eVar.add(zzj, (Object) null);
        eVar.add(zzk, (Object) null);
        eVar.add(zzl, (Object) null);
        eVar.add(zzm, (Object) null);
        eVar.add(zzn, zzpnVar.zzd());
        eVar.add(zzo, zzpnVar.zze());
        eVar.add(zzp, (Object) null);
        eVar.add(zzq, (Object) null);
        eVar.add(zzr, (Object) null);
        eVar.add(zzs, (Object) null);
        eVar.add(zzt, (Object) null);
        eVar.add(zzu, (Object) null);
        eVar.add(zzv, (Object) null);
        eVar.add(zzw, (Object) null);
        eVar.add(zzx, (Object) null);
        eVar.add(zzy, (Object) null);
        eVar.add(zzz, (Object) null);
        eVar.add(zzA, (Object) null);
        eVar.add(zzB, (Object) null);
        eVar.add(zzC, (Object) null);
        eVar.add(zzD, (Object) null);
        eVar.add(zzE, (Object) null);
        eVar.add(zzF, (Object) null);
        eVar.add(zzG, (Object) null);
        eVar.add(zzH, (Object) null);
        eVar.add(zzI, (Object) null);
        eVar.add(zzJ, (Object) null);
        eVar.add(zzK, (Object) null);
        eVar.add(zzL, (Object) null);
        eVar.add(zzM, (Object) null);
        eVar.add(zzN, (Object) null);
        eVar.add(zzO, (Object) null);
        eVar.add(zzP, (Object) null);
        eVar.add(zzQ, (Object) null);
        eVar.add(zzR, (Object) null);
        eVar.add(zzS, zzpnVar.zza());
        eVar.add(zzT, (Object) null);
        eVar.add(zzU, (Object) null);
        eVar.add(zzV, (Object) null);
        eVar.add(zzW, (Object) null);
        eVar.add(zzX, (Object) null);
        eVar.add(zzY, (Object) null);
        eVar.add(zzZ, (Object) null);
        eVar.add(zzaa, (Object) null);
        eVar.add(zzab, (Object) null);
        eVar.add(zzac, (Object) null);
        eVar.add(zzad, (Object) null);
        eVar.add(zzae, (Object) null);
        eVar.add(zzaf, (Object) null);
        eVar.add(zzag, (Object) null);
        eVar.add(zzah, (Object) null);
        eVar.add(zzai, (Object) null);
        eVar.add(zzaj, (Object) null);
        eVar.add(zzak, (Object) null);
        eVar.add(zzal, (Object) null);
        eVar.add(zzam, (Object) null);
        eVar.add(zzan, (Object) null);
        eVar.add(zzao, (Object) null);
        eVar.add(zzap, (Object) null);
        eVar.add(zzaq, (Object) null);
        eVar.add(zzar, (Object) null);
        eVar.add(zzas, (Object) null);
        eVar.add(zzat, (Object) null);
        eVar.add(zzau, (Object) null);
        eVar.add(zzav, (Object) null);
        eVar.add(zzaw, (Object) null);
        eVar.add(zzax, (Object) null);
        eVar.add(zzay, (Object) null);
        eVar.add(zzaz, (Object) null);
        eVar.add(zzaA, (Object) null);
        eVar.add(zzaB, (Object) null);
        eVar.add(zzaC, (Object) null);
        eVar.add(zzaD, (Object) null);
        eVar.add(zzaE, (Object) null);
        eVar.add(zzaF, (Object) null);
        eVar.add(zzaG, (Object) null);
        eVar.add(zzaH, (Object) null);
        eVar.add(zzaI, (Object) null);
        eVar.add(zzaJ, (Object) null);
        eVar.add(zzaK, (Object) null);
        eVar.add(zzaL, (Object) null);
        eVar.add(zzaM, (Object) null);
        eVar.add(zzaN, (Object) null);
        eVar.add(zzaO, (Object) null);
        eVar.add(zzaP, (Object) null);
        eVar.add(zzaQ, (Object) null);
        eVar.add(zzaR, (Object) null);
        eVar.add(zzaS, (Object) null);
        eVar.add(zzaT, (Object) null);
        eVar.add(zzaU, (Object) null);
        eVar.add(zzaV, (Object) null);
        eVar.add(zzaW, (Object) null);
        eVar.add(zzaX, (Object) null);
        eVar.add(zzaY, (Object) null);
        eVar.add(zzaZ, zzpnVar.zzf());
        eVar.add(zzba, (Object) null);
        eVar.add(zzbb, (Object) null);
        eVar.add(zzbc, (Object) null);
    }
}
